# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb773ec16e92b06464e5161e1f560c441aa531ebd75b0f425a6e16ebc058e82b75983a0c00c6934b16cbb6d582bc0f5d9d66299b796f2956f17de857f3d55b53

test:
  secret_key_base: f04ea2e9b20257cc6d2ace8d6709da25f89118687aa615976c4d6ad0ca3add8368fe27d247b8edec8df51e400d63f3403cdeae401b72a184b251957c22474fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
